version: '3.8'

services:
  db-server:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: defaultdb
    ports:
      - "5435:5432"
    volumes:
      - ./infra/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d defaultdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    build:
      context: ./backend/users-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db-server:5432/users_db
    depends_on:
      db-server:
        condition: service_healthy
    volumes:
      - ./backend/users-service:/app

  orders-service:
    build:
      context: ./backend/orders-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db-server:5432/orders_db
      - USERS_SERVICE_URL=http://users-service:8000
    depends_on:
      db-server:
        condition: service_healthy
    volumes:
      - ./backend/orders-service:/app

  shell-ui:
    build:
      context: ./frontend/shell-ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/shell-ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_USE_POLLING=true
    depends_on:
      - orders-ui

  orders-ui:
    build:
      context: ./frontend/orders-ui
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/orders-ui:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  catalog-service:
    build:
      context: ./backend/catalog-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db-server:5432/catalog_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db-server:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/catalog-service:/app

volumes:
  postgres_data:

