name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and Test Users Service
        working-directory: ./backend/users-service
        run: |
          pip install -r requirements.txt
          pytest test_main.py
      - name: Install and Test Orders Service
        working-directory: ./backend/orders-service
        run: |
          pip install -r requirements.txt
          pytest test_main.py
      - name: Install and Test Catalog Service
        working-directory: ./backend/catalog-service
        run: |
          pip install -r requirements.txt
          pytest test_main.py

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Build Orders MFE
        working-directory: ./frontend/orders-ui
        run: |
          npm install
          npm run build
      - name: Install and Build Shell MFE
        working-directory: ./frontend/shell-ui
        run: |
          npm install
          npm run build
