name: E-Commerce CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [users-service, orders-service, catalog-service]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        env:
          TESTING: "true"
        run: |
          cd backend/${{ matrix.service }}
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run Tests
        env:
          TESTING: "true"
        run: |
          cd backend/${{ matrix.service }}
          pytest -v